# Funding for this fork (goatbot_ajmaul_83)
github: [mdajmaul]

# Original GoatBot V2 author - please support him too!
# github: [ntkhang03]
# custom: ["https://www.paypal.com/paypalme/ntkhang03", "https://www.buymeacoffee.com/ntkhang03"]
